# This example uses yaml anchors which allows to name keys
# and re-use for multiple keys in a flexible way.
# Also see https://github.com/Mic92/dotfiles/blob/master/nixos/.sops.yaml
# for a more complex example
keys:
  - &notarock 134FCC2ED75E912E9FB3BF052D7A7E5ABB96084F
creation_rules:
  - path_regex: 'secrets/[^/]+\.yaml$'
    key_groups:
    - pgp:
      - *notarock
